### ISSUE TITLE
The caught error stack is modified after interceptors 

### ISSUE THREAD

**Issue by cbrevik** [svsool/axios-better-stacktrace#1]
Hi, thanks for the great lib! One issue I've found is that other interceptors which you attach to your Axios instance runs before the patched code catches the error. This is by design, but it means we do not get the modified stack trace in our interceptors. 

We're using an error-interceptor to handle logging across different API calls. Would there be some way to attach the "top most error" to the request config object, so we can resolve it in the interceptor by way of `error.config.topmostError` or something?

**Comment by svsool** [comment]
Hi, I think it should be possible as you described it, I'll try to take a look later this week.

**Comment by svsool** [comment]
[v1.2.0](https://www.npmjs.com/package/axios-better-stacktrace) version was just released with `exposeTopmostErrorViaConfig` option which can be used as following:

```javascript
axiosBetterStacktrace(axiosAgent, { exposeTopmostErrorViaConfig: true });

axios.interceptors.response.use(config => config, (result) => {
  console.error(result.config.topmostError);

  return result;
});

axios.get('https://npmjs.com/<not-found>/');
```

Feel free to reopen this issue if you encounter any problems.

**Comment by cbrevik** [comment]
Awesome, thanks @svsool! I'll test it out and see how it works

**Comment by svsool** [comment]
I gave it another try, and with version [v2.0.0](https://github.com/svsool/axios-better-stacktrace), `exposeTopmostErrorViaConfig ` option became obsolete. An error callback in response interceptor should get an error with enhanced stack trace directly now, so no need to use `error.config.topmostError`, `error` should have it already.
