### ISSUE TITLE
ESM dist doesn't have .d.ts file exported

### ISSUE THREAD

**Issue by pravinthan** [svsool/axios-better-stacktrace#12]
The CJS dist has the .d.ts types file exported, but the ESM one doesn't, causing typescript to think that there are no types for this package

**Comment by svsool** [comment]
was unable to reproduce, tried on this ESM setup [archive.zip](https://github.com/svsool/axios-better-stacktrace/files/11276054/archive.zip), build comes with types onboard.

```
ls -l node_modules/axios-better-stacktrace/lib/cjs | rg 'axiosBetterStacktrace.d.ts'
-rw-r--r--  1 user  staff   506 19 Apr 20:21 axiosBetterStacktrace.d.ts
```

it would be good if you provide repro of this issue

**Comment by razor-x** [comment]
@svsool Thanks for merging the fix, can you publish a new release? Thanks.

**Comment by svsool** [comment]
published ✅
