### ISSUE TITLE
ESM default export + CommonJS transpilation

### ISSUE THREAD

**Issue by Nowadays** [svsool/axios-better-stacktrace#3]
Hi, it's me again;

I may have spoken too soon when I said it wasn't a deal breaker 😬

In a node ESM project, if Jest is used as the test framework, you need to transpile the code to CommonJS because Jest doesn't support Esm as of now.

But due to the fact that the exported function is imported as a `default` property of the imported object, once you transpile the code it ends up like this: 

![image](https://user-images.githubusercontent.com/4912348/110003407-a1aaa600-7d16-11eb-9f21-7b1c8be6ed45.png)

Which of course doesn't work. Since I've never used Typescript I don't know how to setup the compiler to export the function as `default` and not as a `default` property of the imported object.

My best bet is that you know how to fix this 😂

**Comment by Nowadays** [comment]
I stand corrected:

When imported like that: `import { default as axiosBetterStacktrace } from 'axios-better-stacktrace';` it works, I don't have the answer as to why though.

Closing... Sorry.

**Comment by svsool** [comment]
Hi, thanks for the contribution! I'll take a look.

> you need to transpile the code to CommonJS because Jest doesn't support Esm as of now.

Have you tried to exclude `node_modules` from transpilation? It seems that module was double transpalied.

**Comment by Nowadays** [comment]
Well, the issue is that in a native ESM env doing:

`import {default as axiosBetterStacktrace } from 'axiosBetterStacktrace';` 

is actually the equivalent of:

`import axiosBetterStacktrace from 'axiosBetterStacktrace';` 

After importing the module, the function must be used as follow:

`axiosBetterStacktrace.default(instance);` So when it gets transpiled it ends up as:

`_axiosBetterStacktrace.default.default(instance);` which of course doesn't work.

There is no double transpilation

**Comment by Nowadays** [comment]
The fastest way and less intrusive way to fix this issue would be to replace:

`export default axiosBetterStacktrace` to `export = axiosBetterStacktrace`; in `src/axiosBetterStacktrace.ts`

Where the output would be: 

`module.exports = axiosBetterStacktrace;` which works both in CJS and ESM, and would not require using `axiosBetterStacktrace.default` in an ESM env

I can edit the PR to do that, it's the best of both world

**Comment by Nowadays** [comment]
Can confirm it works nicely in ESM, thank you @svsool.

Closing https://github.com/svsool/axios-better-stacktrace/pull/6 and this issue. Have a nice day.
