### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by RinatValiullov** [svsool/axios-better-stacktrace#8]
What did I do:
1. `npm i axios`
2. `npm i axios-better-stacktrace `

Got an error (from report.txt which on screenshot):

![image](https://user-images.githubusercontent.com/9755333/142698839-a0d31323-7b15-443a-9988-4c144c18def3.png)

Updated:

With `--legacy-peer-deps` option to `npm install` library is installed without above error.

Updated 1:

When I install 2 dependencies at once, then no errors occur.
`npm i axios axios-better-stacktrace`

**Comment by svsool** [comment]
Hi, it should be fixed in the latest version.
